services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - ./other-services/.env
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./other-services/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - order-network
    restart: unless-stopped

  # Redis - ใช้สำหรับ cache และ pub/sub
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - order-network
    restart: unless-stopped

  # Users Service - จัดการผู้ใช้และการยืนยันตัวตน
  users-service:
    build:
      context: ./services/users-service
      dockerfile: Dockerfile
    container_name: users_service
    env_file:
      - ./services/users-service/.env
    ports:
      - "3002:3002"
    volumes:
      - ./services/users-service:/app
      - users_node_modules:/app/node_modules
    networks:
      - order-network
    restart: unless-stopped

  # Orders Service - จัดการคำสั่งซื้อ
  orders-service:
    build:
      context: ./services/orders-service  
      dockerfile: Dockerfile
    container_name: orders_service
    env_file:
      - ./services/orders-service/.env
    ports:
      - "3001:3001"
    volumes:
      - ./services/orders-service:/app
      - orders_node_modules:/app/node_modules
    networks:
      - order-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # API Gateway
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    env_file:
      - ./gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - orders-service
      - redis
    volumes:
      - ./gateway:/app
      - gateway_node_modules:/app/node_modules
    networks:
      - order-network
    restart: unless-stopped


# Named volumes สำหรับ เก็บข้อมูลถาวรของแต่ละ service
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  users_service_data:
    driver: local
  users_node_modules:
    driver: local
  orders_node_modules:
    driver: local
  gateway_node_modules:
    driver: local
    
# Network สำหรับให้ services คุยกันได้
networks:
  order-network:
    driver: bridge
    name: order-monitoring-network